### model
model_name_or_path: ../ChatGLM3-main/models/glm-4-9b-chat/   # 相对于程序运行路径，而非文件所在路径

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: cmim23_nom1_ra_train
template: glm4
cutoff_len: 2000    # 1024     # 应该是 ques+ans 的总长度
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/glm4_240928
logging_steps: 500
save_steps: 1042      # = sample_num * max_epoch / (batch_size*acc_steps) / checkpoint_num
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-5    # 1.0e-4
num_train_epochs: 2.0   # 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
#val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: "no"    # steps
eval_steps: 500


